print("Første raden:")
firstRow = input()
print("Andre raden:")
secondRow = input()
print("Tredje raden:")
thirdRow = input()
borderSize = max(len(firstRow),len(secondRow),len(thirdRow))
print()
print("@" * borderSize + "@@@@")
print("@ " + " " * (borderSize - len(firstRow)) + firstRow + " @")
print("@ " + " " * (borderSize - len(secondRow)) + secondRow + " @")
print("@ " + " " * (borderSize - len(thirdRow)) + thirdRow + " @")
print("@" * borderSize + "@@@@")